### ISSUE TITLE
Cannot load model

### ISSUE THREAD

**Issue by Hongtao-Niro** [shamangary/FSA-Net#30]
Thanks for your code and model, it works like a charm!

Just a strange thing I noticed when I tried to convert the average model (like what you did in the demo script) to a tf frozen graph. Basically I loaded the three models (`capsule`, `var_capsule`, `noS_capsual`) and average their outputs, and create a new model using the averaged output.

The problem is I can save and load any of your pretrained model, but as soon as I add anything on top of it (even some dummy layers), `load_model` will fail. Below are my dummy testing code to reproduce the issue.

Saving and loading pretrained model works as expected.
```python
import numpy as np
from keras import backend as K
from keras.layers import Maximum, Input
from keras.models import Model, load_model

from lib.FSANET_model import *

# load a model the same way as you did.
num_capsule = 3
dim_capsule = 16
routings = 2
stage_num = [3,3,3]
lambda_d = 1
num_classes = 3
image_size = 64
num_primcaps = 7*3
m_dim = 5
S_set = [num_capsule, dim_capsule, routings, num_primcaps, m_dim]

model1 = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
weight_file1 = 'pre-trained/300W_LP_models/fsanet_capsule_3_16_2_21_5/fsanet_capsule_3_16_2_21_5.h5'
model1.load_weights(weight_file1)
print('Finished loading model 1.')


# save and load the model the same way as you did
model1.save("temp.hd5")
K.clear_session()
sess = K.get_session()
K.set_learning_phase(0)
new_model = load_model("temp.hd5")  # model will load successfully

# inspect the loaded model
print(f"Model inputs information - {new_model.inputs}")
print(f"Model outputs information - {new_model.outputs}")
```

However, when I tried to add a dummy maximum layer, `load_model` will fail.
```python
import numpy as np
from keras import backend as K
from keras.layers import Maximum, Input
from keras.models import Model, load_model

from lib.FSANET_model import *

# load a model the same way as you did.
num_capsule = 3
dim_capsule = 16
routings = 2
stage_num = [3,3,3]
lambda_d = 1
num_classes = 3
image_size = 64
num_primcaps = 7*3
m_dim = 5
S_set = [num_capsule, dim_capsule, routings, num_primcaps, m_dim]

model1 = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
weight_file1 = 'pre-trained/300W_LP_models/fsanet_capsule_3_16_2_21_5/fsanet_capsule_3_16_2_21_5.h5'
model1.load_weights(weight_file1)
print('Finished loading model 1.')

# add dummy layer on top of model. I did it in the same way as you did in the demo scripts.
inputs = Input(shape=(64,64,3))
x = model1(inputs)
xx = Maximum()([x, x])  # xx is the same as x
dummy_model = Model(inputs=inputs, outputs=xx)
dummy_model.summary()

# test if the dummy model works
dummy_image = np.ones([1, 64, 64, 3], dtype=np.float32)
dummy_out = dummy_model.predict(dummy_image)
model_out = model1.predict(dummy_image)
assert np.array_equal(model_out, dummy_out)   # the dummy model works just fine


# save and load the dummy model the same way as before
dummy_model.save("temp_dummy.hd5")
K.clear_session()
sess = K.get_session()
K.set_learning_phase(0)
new_model = load_model("temp_dummy.hd5")   # Error here!!!

# inspect the loaded model
print(f"Model inputs information - {new_model.inputs}")
print(f"Model outputs information - {new_model.outputs}")
```
The error message is:
```
Traceback (most recent call last):
  File "training_and_testing/temp_dummy.py", line 44, in <module>
    new_model = load_model("temp_dummy.hd5")  # model will load successfully  # Error here!!!
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    reshape=False)
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/home/hongtao/miniconda3/envs/ml-source/lib/python3.7/site-packages/keras/engine/saving.py", line 800, in preprocess_weights_for_loading
    elif layer_weights_shape != weights[0].shape:
IndexError: list index out of range

```

I have tried to add the same dummy layer on top of the official keras mobilenet model, and no error during saving and loading. Therefore I'm guessing that some operations in your model might be the cause to this issue, can you help me with it? Thanks!

**Comment by Hongtao-Niro** [comment]
### **Updates**
I tried the same thing with the keras `inception_resnet_v2` model, and no errors:
```python
model = keras.applications.inception_resnet_v2.InceptionResNetV2(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
print(model.inputs)

# add dummy layer on top of model. I did it in the same way as how you created the average model.
inputs = Input(shape=(299,299,3))
x = model(inputs)
xx = Maximum()([x, x])  # xx is the same as x
dummy_model = Model(inputs=inputs, outputs=xx)

# test is dummy model works
dummy_image = np.ones([1, 299, 299, 3], dtype=np.float32)
dummy_out = dummy_model.predict(dummy_image)
# print(dummy_out)
model_out = model.predict(dummy_image)
# print(model_out)
assert np.array_equal(model_out, dummy_out)   # the dummy model works just fine

# save and load the dummy model the same way as before
dummy_model.save("temp_dummy.hd5")
K.clear_session()
sess = K.get_session()
K.set_learning_phase(0)
new_model = load_model("temp_dummy.hd5", compile=False)  # Error here!!!

# inspect the loaded model
print(f"Model inputs information - {new_model.inputs}")
print(f"Model outputs information - {new_model.outputs}")
```

**Comment by shamangary** [comment]
Hello, I am no expert of the keras and tensorflow structure, but it seems to me that it is not a resolvable issue.
https://github.com/keras-team/keras/issues/10428
Therefore, I would suggest you save separate sub-models and load them separately.

**Comment by Hongtao-Niro** [comment]
Thanks for the reference. I'll settle on loading the three models separately for now. Will keep you updated if I find anything new.
