### ISSUE TITLE
models in ONNX format !

### ISSUE THREAD

**Issue by prnvjb** [shamangary/FSA-Net#37]
Did anybody able to convert these models into onnx format?

**Comment by guyibang** [comment]
I would like to konw too

**Comment by guyibang** [comment]
@prnvjb Did you make sucess to convert the keras model to onnx model?

**Comment by prnvjb** [comment]
yes!

**Comment by guyibang** [comment]
@prnvjb How did you do it?Could you share the onnx model with me or teach me how to do it?

**Comment by guyibang** [comment]
@prnvjb I had try to follow the keras_to_tf.py steps,define the new model and load weights first,then use the keras2onnx tools to convert the model,such as
`model = Model(inputs=inputs, outputs=avg_model)`
`onnx_model = keras2onnx.convert_keras(model, model.name)`
`temp_model_file = './model.onnx'`
`onnx.save_model(onnx_model, temp_model_file)`
but I always got this error,part of info is like:
`Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
The layer <lib.FSANET_model.FeatSliceLayer object at 0x7f90a017f978> doesn't have a specific converter, fall back.
I1227 16:14:55.018830 140268226275136 parser.py:240] The layer <lib.FSANET_model.FeatSliceLayer object at 0x7f90a017f978> doesn't have a specific converter, fall back.
The layer <lib.capsulelayers.CapsuleLayer object at 0x7f90a017fc50> doesn't have a specific converter, fall back.
I1227 16:14:58.592233 140268226275136 parser.py:240] The layer <lib.capsulelayers.CapsuleLayer object at 0x7f90a017fc50> doesn't have a specific converter, fall back.
The layer <lib.FSANET_model.MatrixMultiplyLayer object at 0x7f90a02990b8> doesn't have a specific converter, fall back.
I1227 16:14:59.592540 140268226275136 parser.py:240] The layer <lib.FSANET_model.MatrixMultiplyLayer object at 0x7f90a02990b8> doesn't have a specific converter, fall back.
E1227 16:15:02.090079 140268226275136 tfonnx.py:355] Failed to convert node TFNodes17/ssr_Cap_model/caps/transpose
OP=Transpose
Name=TFNodes17/ssr_Cap_model/caps/transpose
Inputs:
	TFNodes17/ssr_Cap_model/caps/zeros:0=ConstantOfShape, [-1, 3, 21], 1
	TFNodes17/ssr_Cap_model/caps/concat:0=Concat, [3], 6
Outpus:
	TFNodes17/ssr_Cap_model/caps/transpose:0=[-1, 21, 3], 1
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/onnx_opset/tensor.py", line 201, in version_1
    utils.make_sure(False, "perm can't be dynamic in ONNX")
  File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: perm can't be dynamic in ONNX
E1227 16:15:02.092512 140268226275136 tfonnx.py:355] Failed to convert node TFNodes17/ssr_Cap_model/caps/transpose_1
OP=Transpose
Name=TFNodes17/ssr_Cap_model/caps/transpose_1
Inputs:
	TFNodes17/ssr_Cap_model/caps/Softmax:0=Softmax, [-1, 21, 3], 1
	TFNodes17/ssr_Cap_model/caps/concat_1:0=Concat, [3], 6
Outpus:
	TFNodes17/ssr_Cap_model/caps/transpose_1:0=[-1, 3, 21], 1`

Have you ever had this error?Or could you tell me how did you do to sucess to convert the keras model to onnx model?

**Comment by guyibang** [comment]
> @prnvjb I had try to follow the keras_to_tf.py steps,define the new model and load weights first,then use the keras2onnx tools to convert the model,such as
> `model = Model(inputs=inputs, outputs=avg_model)`
> `onnx_model = keras2onnx.convert_keras(model, model.name)`
> `temp_model_file = './model.onnx'`
> `onnx.save_model(onnx_model, temp_model_file)`
> 
> but I always got this error,part of info is like:
> `Instructions for updating: Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name` The layer <lib.FSANET_model.FeatSliceLayer object at 0x7f90a017f978> doesn't have a specific converter, fall back. I1227 16:14:55.018830 140268226275136 parser.py:240] The layer <lib.FSANET_model.FeatSliceLayer object at 0x7f90a017f978> doesn't have a specific converter, fall back. The layer <lib.capsulelayers.CapsuleLayer object at 0x7f90a017fc50> doesn't have a specific converter, fall back. I1227 16:14:58.592233 140268226275136 parser.py:240] The layer <lib.capsulelayers.CapsuleLayer object at 0x7f90a017fc50> doesn't have a specific converter, fall back. The layer <lib.FSANET_model.MatrixMultiplyLayer object at 0x7f90a02990b8> doesn't have a specific converter, fall back. I1227 16:14:59.592540 140268226275136 parser.py:240] The layer <lib.FSANET_model.MatrixMultiplyLayer object at 0x7f90a02990b8> doesn't have a specific converter, fall back. E1227 16:15:02.090079 140268226275136 tfonnx.py:355] Failed to convert node TFNodes17/ssr_Cap_model/caps/transpose OP=Transpose Name=TFNodes17/ssr_Cap_model/caps/transpose Inputs: TFNodes17/ssr_Cap_model/caps/zeros:0=ConstantOfShape, [-1, 3, 21], 1 TFNodes17/ssr_Cap_model/caps/concat:0=Concat, [3], 6 Outpus: TFNodes17/ssr_Cap_model/caps/transpose:0=[-1, 21, 3], 1 Traceback (most recent call last): File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping func(g, node, **kwargs) File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/onnx_opset/tensor.py", line 201, in version_1 utils.make_sure(False, "perm can't be dynamic in ONNX") File "/opt/anaconda3/lib/python3.6/site-packages/keras2onnx/ktf2onnx/tf2onnx/utils.py", line 290, in make_sure raise ValueError("make_sure failure: " + error_msg % args) ValueError: make_sure failure: perm can't be dynamic in ONNX E1227 16:15:02.092512 140268226275136 tfonnx.py:355] Failed to convert node TFNodes17/ssr_Cap_model/caps/transpose_1 OP=Transpose Name=TFNodes17/ssr_Cap_model/caps/transpose_1 Inputs: TFNodes17/ssr_Cap_model/caps/Softmax:0=Softmax, [-1, 21, 3], 1 TFNodes17/ssr_Cap_model/caps/concat_1:0=Concat, [3], 6 Outpus: TFNodes17/ssr_Cap_model/caps/transpose_1:0=[-1, 3, 21], 1`
> 
> Have you ever had this error?Or could you tell me how did you do to sucess to convert the keras model to onnx model?

I was sucessed to convert the pb model to onnx model by using tf2onnx,reference to  [https://github.com/onnx/tensorflow-onnx/issues/650](url),adding the parameters of `--fold_const` in the command line finally help me to solved this problem.

**Comment by GHLab** [comment]
@guyibang Did you see this error during onnx converting? 
"ValueError: Input 0 of node model_1/ssr_Cap_model/caps/map/while/MatMul/ReadVariableOp/Enter was passed float from caps/W:0 incompatible with expected resource."
I did below command.
python -m tf2onnx.convert --input fsanet.pb --inputs X:0[64,64,3] --outputs output:0 --output fsanet.onnx --verbose
If you resolved it, please let me know the way.

**Comment by gabrielibagon** [comment]
I'm also having an issue converting the frozen graph from .pb to onnx.

@guyibang - can you please tell us the `tf2onnx` version and command that you used?

I'm using the following command, and getting an error below:

**Command**:
`python -m tf2onnx.convert--input fsanet_var_capsule_3_16_2_21_5.pb --output=fsanet.onnx --inputs input_1:0 --outputs pred_pose/mul_24:0  --opset=11 --fold_const --verbose`

**Error**:
```
2020-05-06 21:43:17,722 - INFO - tf2onnx: inputs: ['input_1:0']
2020-05-06 21:43:17,722 - INFO - tf2onnx: outputs: ['pred_pose/mul_24:0']
2020-05-06 21:43:17,886 - INFO - tf2onnx.tfonnx: Using tensorflow=2.0.0, onnx=1.6.0, tf2onnx=1.6.0/8b8d5e
2020-05-06 21:43:17,886 - INFO - tf2onnx.tfonnx: Using opset <onnx, 11>
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_1/FusedBatchNormV3_1: ssr_G_model/batch_normalization_1/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_8/FusedBatchNormV3_1: ssr_G_model/batch_normalization_8/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_2/FusedBatchNormV3_1: ssr_G_model/batch_normalization_2/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_9/FusedBatchNormV3_1: ssr_G_model/batch_normalization_9/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_3/FusedBatchNormV3_1: ssr_G_model/batch_normalization_3/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_10/FusedBatchNormV3_1: ssr_G_model/batch_normalization_10/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_4/FusedBatchNormV3_1: ssr_G_model/batch_normalization_4/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_11/FusedBatchNormV3_1: ssr_G_model/batch_normalization_11/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_5/FusedBatchNormV3_1: ssr_G_model/batch_normalization_5/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_12/FusedBatchNormV3_1: ssr_G_model/batch_normalization_12/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_6/FusedBatchNormV3_1: ssr_G_model/batch_normalization_6/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_13/FusedBatchNormV3_1: ssr_G_model/batch_normalization_13/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_7/FusedBatchNormV3_1: ssr_G_model/batch_normalization_7/FusedBatchNormV3_1:5
2020-05-06 21:43:18,022 - WARNING - tf2onnx.shape_inference: Cannot infer shape for ssr_G_model/batch_normalization_14/FusedBatchNormV3_1: ssr_G_model/batch_normalization_14/FusedBatchNormV3_1:5
2020-05-06 21:43:18,892 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2020-05-06 21:43:19,115 - ERROR - tf2onnx.tfonnx: Failed to convert node ssr_S_model/feat_S_model_2/moments_layer_1/moments/variance
OP=ReduceMean
Name=ssr_S_model/feat_S_model_2/moments_layer_1/moments/variance
Inputs:
	ssr_S_model/feat_S_model_2/moments_layer_1/moments/SquaredDifference__297:0=Mul, None, 1
	ssr_S_model/feat_S_model_2/moments_layer_1/moments/variance/reduction_indices:0=Const, [], 6
Outpus:
	ssr_S_model/feat_S_model_2/moments_layer_1/moments/variance:0=[-1, 8, 8, 1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 266, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 55, in version_11
    cls.version_1(ctx, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 40, in version_1
    raise ValueError("reduce_op: cannot have negative axis because we don't know input rank")
ValueError: reduce_op: cannot have negative axis because we don't know input rank
2020-05-06 21:43:19,127 - ERROR - tf2onnx.tfonnx: Failed to convert node ssr_S_model/feat_S_model_1/moments_layer_1/moments/variance
OP=ReduceMean
Name=ssr_S_model/feat_S_model_1/moments_layer_1/moments/variance
Inputs:
	ssr_S_model/feat_S_model_1/moments_layer_1/moments/SquaredDifference__313:0=Mul, None, 1
	ssr_S_model/feat_S_model_1/moments_layer_1/moments/variance/reduction_indices:0=Const, [], 6
Outpus:
	ssr_S_model/feat_S_model_1/moments_layer_1/moments/variance:0=[-1, 8, 8, 1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 266, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 55, in version_11
    cls.version_1(ctx, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 40, in version_1
    raise ValueError("reduce_op: cannot have negative axis because we don't know input rank")
ValueError: reduce_op: cannot have negative axis because we don't know input rank
2020-05-06 21:43:19,142 - ERROR - tf2onnx.tfonnx: Failed to convert node ssr_S_model/feat_S_model/moments_layer_1/moments/variance
OP=ReduceMean
Name=ssr_S_model/feat_S_model/moments_layer_1/moments/variance
Inputs:
	ssr_S_model/feat_S_model/moments_layer_1/moments/SquaredDifference__333:0=Mul, None, 1
	ssr_S_model/feat_S_model/moments_layer_1/moments/variance/reduction_indices:0=Const, [], 6
Outpus:
	ssr_S_model/feat_S_model/moments_layer_1/moments/variance:0=[-1, 8, 8, 1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 266, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 55, in version_11
    cls.version_1(ctx, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 40, in version_1
    raise ValueError("reduce_op: cannot have negative axis because we don't know input rank")
ValueError: reduce_op: cannot have negative axis because we don't know input rank
2020-05-06 21:43:19,178 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 153, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 485, in process_tf_graph
    raise exceptions[0]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 266, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 55, in version_11
    cls.version_1(ctx, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/reduction.py", line 40, in version_1
    raise ValueError("reduce_op: cannot have negative axis because we don't know input rank")
ValueError: reduce_op: cannot have negative axis because we don't know input rank
```

**Comment by awl-ngoc-son** [comment]
have anyone converted model to ONNX successfully? I have the same problem :(((

**Comment by VioletEvergardenYYH** [comment]
I have the same problem :((( Don't know how to modify a pb file's initializer

**Comment by shamangary** [comment]
Hello, sorry I wasn't really maintaining this repo anymore and I am not familiar with ONNX, but luckily I found someone else has done the ONNX thing for me :)))). 

https://github.com/xuhao1/FOXTracker/ 

Please go check the awesome page, and I believe there is an ONNX FSANet variant (https://github.com/xuhao1/FOXTracker/tree/master/assets) for the VR flight application.
