### ISSUE TITLE
Question about training FSANET_Capsule

### ISSUE THREAD

**Issue by xxxillllll** [shamangary/FSA-Net#50]
It is fine when training SSRNET_MT, but when training FSANET_Capsule, an error comes.

Traceback (most recent call last):
  File "FSANET_train.py", line 299, in <module>
    main()
  File "FSANET_train.py", line 132, in main
    model = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
  File "..\lib\FSANET_model.py", line 444, in __call__
    ssr_Cap_list = ssr_aggregation_model(ssr_primcaps)
  File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2061, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2265, in run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("reshape_8/Reshape:0", shape=(?, ?), dtype=float32)

**Comment by PotentialPie** [comment]
> It is fine when training SSRNET_MT, but when training FSANET_Capsule, an error comes.
> 
> ```
> Traceback (most recent call last):
>   File "FSANET_train.py", line 299, in <module>
>     main()
>   File "FSANET_train.py", line 132, in main
>     model = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
>   File "..\lib\FSANET_model.py", line 444, in __call__
>     ssr_Cap_list = ssr_aggregation_model(ssr_primcaps)
>   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 603, in __call__
>     output = self.call(inputs, **kwargs)
>   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2061, in call
>     output_tensors, _, _ = self.run_internal_graph(inputs, masks)
>   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2265, in run_internal_graph
>     assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
> AssertionError: Could not compute output Tensor("reshape_8/Reshape:0", shape=(?, ?), dtype=float32)
> ```
> 
> And my environment is the same as the environment you list.
> Thank you!

I have the same problem as you.
The environment is the same.

**Comment by xxxillllll** [comment]
> > It is fine when training SSRNET_MT, but when training FSANET_Capsule, an error comes.
> > ```
> > Traceback (most recent call last):
> >   File "FSANET_train.py", line 299, in <module>
> >     main()
> >   File "FSANET_train.py", line 132, in main
> >     model = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
> >   File "..\lib\FSANET_model.py", line 444, in __call__
> >     ssr_Cap_list = ssr_aggregation_model(ssr_primcaps)
> >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 603, in __call__
> >     output = self.call(inputs, **kwargs)
> >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2061, in call
> >     output_tensors, _, _ = self.run_internal_graph(inputs, masks)
> >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2265, in run_internal_graph
> >     assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
> > AssertionError: Could not compute output Tensor("reshape_8/Reshape:0", shape=(?, ?), dtype=float32)
> > ```
> > 
> > 
> > And my environment is the same as the environment you list.
> > Thank you!
> 
> I have the same problem as you.
> The environment is the same.

My solution is to use py3.6 and change keras,tf... correspondingly. 
The environment the writer lists, is not suitable for the latest code.

**Comment by PotentialPie** [comment]
> > > It is fine when training SSRNET_MT, but when training FSANET_Capsule, an error comes.
> > > ```
> > > Traceback (most recent call last):
> > >   File "FSANET_train.py", line 299, in <module>
> > >     main()
> > >   File "FSANET_train.py", line 132, in main
> > >     model = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
> > >   File "..\lib\FSANET_model.py", line 444, in __call__
> > >     ssr_Cap_list = ssr_aggregation_model(ssr_primcaps)
> > >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 603, in __call__
> > >     output = self.call(inputs, **kwargs)
> > >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2061, in call
> > >     output_tensors, _, _ = self.run_internal_graph(inputs, masks)
> > >   File "E:\Anaconda3\envs\bishe\lib\site-packages\keras\engine\topology.py", line 2265, in run_internal_graph
> > >     assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
> > > AssertionError: Could not compute output Tensor("reshape_8/Reshape:0", shape=(?, ?), dtype=float32)
> > > ```
> > > 
> > > 
> > > And my environment is the same as the environment you list.
> > > Thank you!
> > 
> > 
> > I have the same problem as you.
> > The environment is the same.
> 
> My solution is to use py3.6 and change keras,tf... correspondingly.
> The environment the writer lists, is not suitable for the latest code.

I just reinstalled the environment and everything went well....
There must be some problems but I haven't found.
