### ISSUE TITLE
There is a problem when run demo_FSANET_ssd.py 

### ISSUE THREAD

**Issue by dony1556** [shamangary/FSA-Net#53]
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From e:\sundwpyworkspace\vscode\FSA-Net\demo\lib\capsulelayers.py:195: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
Traceback (most recent call last):
  File "e:/sundwpyworkspace/vscode/FSA-Net/demo/demo_FSANET_ssd.py", line 216, in <module>
    main()
  File "e:/sundwpyworkspace/vscode/FSA-Net/demo/demo_FSANET_ssd.py", line 126, in main
    model1 = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
  File "e:\sundwpyworkspace\vscode\FSA-Net\demo\lib\FSANET_model.py", line 444, in __call__
    ssr_Cap_list = ssr_aggregation_model(ssr_primcaps)
  File "D:\ProgramData\Anaconda3\envs\face_tf_sundw\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\face_tf_sundw\lib\site-packages\keras\engine\topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "D:\ProgramData\Anaconda3\envs\face_tf_sundw\lib\site-packages\keras\engine\topology.py", line 2289, in run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("reshape_8/Reshape:0", shape=(?, ?), dtype=float32)

**Comment by PotentialPie** [comment]
You can try to use keras 2.2.4 and tensorflow 1.10.0.
