### ISSUE TITLE
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

### ISSUE THREAD

**Issue by Algabri** [shamangary/FSA-Net#78]
When I run training code for `--model_type` 2,3,5,6,8 and 9. Also, demo codes. I got this error:

```
Traceback (most recent call last):
  File "/home/redhwan/2/HPE/FSA-Net/demo/demo_FSANET_mtcnn.py", line 205, in <module>
    main()
  File "/home/redhwan/2/HPE/FSA-Net/demo/demo_FSANET_mtcnn.py", line 125, in main
    model1 = FSA_net_Capsule(image_size, num_classes,
  File "/home/redhwan/2/HPE/FSA-Net/demo/../lib/FSANET_model.py", line 431, in __call__
    ssr_S_model = self.ssr_S_model_build(num_primcaps=self.num_primcaps,m_dim=self.m_dim)           
  File "/home/redhwan/2/HPE/FSA-Net/demo/../lib/FSANET_model.py", line 370, in ssr_S_model_build
    feat_S_model = self.ssr_feat_S_model_build(m_dim)
  File "/home/redhwan/2/HPE/FSA-Net/demo/../lib/FSANET_model.py", line 360, in ssr_feat_S_model_build
    SR_matrix = Dense(m_dim*(self.map_xy_size*self.map_xy_size*3),activation='sigmoid')(feat_preS)
  File "/home/redhwan/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/home/redhwan/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/redhwan/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1154, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```
`tensorflow  ==2.2.0`

**Comment by Algabri** [comment]
I fixed it by updating tensorflow  ==2.2.0 to tensorflow  ==2.3 and numpy-1.20.0
